runtime: nodejs10
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  DB_USER: root
  DB_PASS: main
  DB_NAME: autismdb
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  CLOUD_SQL_CONNECTION_NAME: autismproject:us-west2:main-db
